PACKAGE_NAMES = dewi

#
# Don't need to change anything below this line
#

NOSE ?= $(shell which nosetests)
NOSE_TEST_PATHS ?= $(PACKAGE_NAMES)

REPORTS_DIR = doc/reports

PYCODESTYLE ?= $(shell which python) -m pycodestyle
PYLINT ?= $(shell which pylint)

PYLINT_DIR = $(REPORTS_DIR)/pylint
PYLINT_OUTPUT = $(PYLINT_DIR)/pylint.out

BEHAVE ?= $(shell which behave) --format progress2
