PACKAGE_NAMES = dewi

#
# Don't need to change anything below this line
#

NOSE ?= $(shell which nosetests-3.4)
NOSE_TEST_PATHS ?= $(PACKAGE_NAMES)

REPORTS_DIR = doc/reports

PEP8 ?= $(shell which pep8-3.4)
PYLINT ?= $(shell which pylint-3.4)

PYLINT_DIR = $(REPORTS_DIR)/pylint
PYLINT_OUTPUT = $(PYLINT_DIR)/pylint.out
